export const DEFAULT_ROOT_PATH = '/admin'
export const INVALID_CREDENTIALS_ERROR_MESSAGE = 'invalidCredentials'
export const ADMINJS_PACKAGE_NAME = 'AdminJS'
export const ADMINJS_ERROR_MESSAGE = 'You have to pass an instance of AdminJS to the buildRouter() function'
export const ADMINJS_ERROR_NAME = 'WrongArgumentError'
export const INITIALIZED_MESSAGE = 'AdminJS: bundle ready'
